package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_rust//rust:rust.bzl", "rust_test")

rust_test(
    name = "mafia_test",
    srcs = ["test.rs"],
    deps = ["//:mafia"],
)
