#!/bin/bash -e

cd "$(dirname "$0")/.."

# Colors
RED="$(tput setaf 1)"
GREEN="$(tput setaf 2)"
RESET="$(tput sgr0)"

cargo fmt -- --check \
    || { printf "\n${RED}ERROR${RESET}: Run \`cargo fmt\` before committing.\n"; exit 1; }

cargo test

printf "\nPresubmits ${GREEN}PASSED${RESET}.\n"
